worker_processes auto; 

events {
    worker_connections 1024; 
}

http {

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # -------- Load Balancer --------
    upstream task_backend {
        least_conn;
        server flask1:8000;
        server flask2:8000;
    }

    # -------- Rate Limiting (must be outside server block) --------
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;


    # -------- HTTP → HTTPS Redirect --------
    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }


    # -------- HTTPS Server --------
    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate     /etc/ssl/certs/selfsigned.crt;
        ssl_certificate_key /etc/ssl/private/selfsigned.key;
        ssl_protocols       TLSv1.2 TLSv1.3;

        # -------- Rate limit applied --------
        limit_req zone=api_limit burst=20;


        # -------- Serve Static Files Directly --------
        location /static/ {
            alias /static/;
        }

        location /api/ {
            proxy_pass http://task_backend;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }


        # -------- Proxy to Flask Backend --------
        location / {

            proxy_pass http://task_backend;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

        }
    }
}